project:
  type: manuscript
  output-dir: docs

title: "ESS 330 Final"
bibliography: references.bib
csl: apa.csl

manuscript:
  article: index.qmd

format:
  html:
    self-contained: true
    comments:
      hypothesis: true
  docx: default
  jats: default

execute:
  echo: true

