---
title: "Land Cover Change"
authors:
  - name: Nina Hayford & Sierra Mattiar
    affiliation: The University
    roles: writing
    corresponding: true
bibliography: references.bib
---

# Altitudinal Climate Change Across the US

## Introduction

In this project, we are addressing how the temperature has changed in the US over the last two decades in relation to different altitudes. This is an important topic to cover because in the realm of climate change, higher altitude regions tend to respond to climate change in complex ways [@Penn_LPS_Online_2024a]. Being able to track these interesting changes will provide us with data to help people understand why these regions respond in certain ways. The data we have might also help us understand the highly impacted areas that might be suffering from the impacts of climate change more than other areas. Another reason why this topic is important to study is the fact that higher altitude areas are more sensitive to climate shifts [@ITT_User_2023a]. With the climate shiftinf rapidly, there is much research to be done to see how sensitive these areas are and in what aspect. Lastly, high altitudes contribute to climate variability and play a role in atmospheric circulation patterns [@ITT_User_2023a] so there could be much more effected by the altitudes than just the climate.

## Data Exploration

We will focus on data components that show this temperature change and compare their altitudes to see if different altitudes are effected by climate change differently. Some of the data we are using is monthly/daily temperature data along with elevation data in the US. We will focus on using spatial data tools within RStudio to help organize the data and compare temperature changes in different areas. We hope to show this through line graphs. We can do this by setting the time period and filtering by region. We will clean and manipulate the data by setting the time period from 2000-2020, handle missing data values, standardizing any data, if necessary, like degrees Fahrenheit to degrees Celsius or vise versa, and organize by months and seasons.

The data for this project was obtained from the NOAA website. The data includes:

-   32_or_cooler.txt: Number of days with minimum temperature ≤ 32°F

-   90_or_higher.txt: Number of days with maximum temperature ≥ 90°F

-   highest_temp.txt: Highest recorded temperature per month

-   lowest.temp.txt: Lowest recorded temperature per month

-   humidity.txt: Annual relative humidity by location

-   nrmavg.txt, nrmmax.txt, and nrmmin.txt: Normal average, maximum, and minimum daily temperatures

-   elevation_US_Cities.csv: elevation data with the peaks and dips of the major US cities

Each dataset includes location information (e.g., city or station), date/year, and the measurement of interest. These will be cross-referenced with elevation data to determine altitudinal patterns.
```{r}

```

## Methods Identification

Within RStudio, we can perform spatial analysis to show regional variations in temperature. We can do this by using mapping tools like ggplot2, sf, or terra. We were also thinking about dividing the data by months and possibly seasonal as well. We will assess how temperature changes over time using line graphs or trend lines, then compare them to the region they are in. We could include more supplemental data like normal temperatures to compare what the temperatures usually look like versus what they are now. We could also include things like humidity because humidity changes a lot in different elevations so it might be something important to keep track of. Some potential challenges we might see in the data is missing values or unavailable pieces of data. It also might have regional variation where not all areas have elevation data so we will not be able to use it. Some potential challenges we see in the methods include the complexity to compare data over two decades across an entire country. So it is very important to focus on organizing and cleaning the data. It also may be hard to strictly distinguish between correlation and causation. Lastly, the selected methods will help us get to our final goal because these methods help us perform spatial and temporal analysis to visualize the data and support our claim. We can also compare our findings to try and find a possible cause or a strong influence for temperature changes.
